<?php

namespace App\Http\Middleware;

use Illuminate\Cookie\Middleware\EncryptCookies as Middleware;

class EncryptCookies extends Middleware
{
    /**
     * The names of the cookies that should not be encrypted.
     *
     * @var array<int, string>
     */
    protected $except = [
        /*
            By default, all cookies generated by Laravel are encrypted and signed so that they can't be modified or read by the client.
            If you would like to disable encryption for a subset of cookies generated by your application, you may use the $except
            property of the App\Http\Middleware\EncryptCookies middleware, which is located in the app/Http/Middleware directory
        */
        'tes-cookie',
        'tes-cookie2'
    ];
}
